steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pipeline-generator', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pipeline-generator']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pipeline-generator'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pipeline-generator'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_API_KEY=${_GOOGLE_API_KEY},GITLAB_URL=${_GITLAB_URL},GITLAB_TOKEN=${_GITLAB_TOKEN}'

images:
  - 'gcr.io/$PROJECT_ID/pipeline-generator'

substitutions:
  _GOOGLE_API_KEY: ''  # Set in Cloud Build triggers
  _GITLAB_URL: ''      # Set in Cloud Build triggers
  _GITLAB_TOKEN: ''    # Set in Cloud Build triggers 