stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - main

test:
  stage: test
  image: $DOCKER_IMAGE
  script:
    - echo "Running tests..."
    - python -m pytest tests/
  only:
    - main

deploy:
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - echo "Deploying to Cloud Run..."
    - gcloud run deploy $CI_PROJECT_NAME --image $DOCKER_IMAGE --platform managed --region us-central1
  only:
    - main 